name: CI Workflow

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
        platform: [x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: make -f Bootstrap.mak linux PLATFORM=${{ matrix.platform }} CONFIG=${{ matrix.config }}
    - name: Test
      run: bin/${{ matrix.config }}/premake5 test --test-all
    - name: Docs check
      run: bin/${{ matrix.config }}/premake5 docs-check
    - name: Upload Artifacts
      if: matrix.config == 'release'
      uses: actions/upload-artifact@v2
      with:
        name: premake-linux-${{ matrix.platform }}
        path: bin/${{ matrix.config }}/
  macosx:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [debug, release]
        platform: [x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: make -f Bootstrap.mak macosx PLATFORM=${{ matrix.platform }} CONFIG=${{ matrix.config }}
    - name: Test
      run: bin/${{ matrix.config }}/premake5 test --test-all
    - name: Docs check
      run: bin/${{ matrix.config }}/premake5 docs-check
    - name: Upload Artifacts
      if: matrix.config == 'release'
      uses: actions/upload-artifact@v2
      with:
        name: premake-macosx-${{ matrix.platform }}
        path: bin/${{ matrix.config }}/
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [debug, release]
        platform: [Win32, x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        $vcvarsall_path = vswhere.exe -find VC\Auxiliary\Build\vcvarsall.bat
        cmd.exe /c "call ""$vcvarsall_path"" x86_amd64 && nmake -f Bootstrap.mak MSDEV=vs2019 windows-msbuild PLATFORM=${{ matrix.platform }} CONFIG=${{ matrix.config }}"
    - name: Test
      run: bin\${{ matrix.config }}\premake5 test --test-all
      shell: cmd
    - name: Docs check
      run: bin\${{ matrix.config }}\premake5 docs-check
      shell: cmd
    - name: Upload Artifacts
      if: matrix.config == 'release'
      uses: actions/upload-artifact@v2
      with:
        name: premake-windows-${{ matrix.platform }}
        path: bin\${{ matrix.config }}\
  source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [release]
        platform: [x64]
    needs: [linux, macosx, windows] # Pass all builds before creating source bundle
    steps:
    - name: Checkout # Need to checkout to get the package action
      uses: actions/checkout@v3
    - name: Download Release
      uses: actions/download-artifact@v3
      with:
        name: premake-linux-${{ matrix.platform }}
    - name: Generate Sources for Push
      if: github.event_name != 'pull_request'
      run: chmod 555 ./premake5 && ./premake5 package ${{ github.head_ref || github.ref_name }} source force
    - name: Generate Sources for Pull Request
      if: github.event_name == 'pull_request'
      run: chmod 555 ./premake5 && ./premake5 package pull/${{ github.event.pull_request.number }}/head source force
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: premake-src
        path: release/
